### ISSUE TITLE
https -> http request 이슈

### ISSUE THREAD

**Issue by changgihong** [sscoderati/SPACUP_SLEP#7]
vercel에 배포를 완료하였으나, vercel 서비스는 https, 프로젝트에서 사용하는 공공 api는 http 프로토콜을 사용하고 있어 요청 오류가 발생 중.
비슷한 서비스인 netlify로의 migration 또한 해당 서비스가 https 프로토콜을 사용하고 있어서 현재 다른 방법 찾는 중...

**Comment by sscoderati** [comment]
현재 시도해본 방법 : 
1. `index.html`에 특정 meta 태그 요소 추가
2. 
3. 
4.

**Comment by changgihong** [comment]
현재 시도해본 방법:
- index.html에 특정 meta 태그 요소 추가
`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">` 를 index.html에 추가해봤음.
-> client-side에서 보내는 http 요청을 https로 변환해주는 기능이라서, 공공 api 측에서 https 연결을 허용하지 않아 해결하지 못했음

- cdn 서버 프록시 설정?
구글링 중에 블로그 글을 발견하고 따라해봤음.
링크 : https://velog.io/@jiheon788/Netlify%EC%97%90%EC%84%9C-HTTPS-HTTP-%ED%86%B5%EC%8B%A0-%ED%95%B4%EA%B2%B0-%EA%B3%BC%EC%A0%95
`/api/* http://{your server URL}/:splat 200` 의 형식으로 http 요청에 대해 redirection 시켜주면, cdn 서버가 proxy를 통해 해당 서버와의 통신을 가능하게 한다는 내용.
시도해보았으나 요청이 이상하게 날아가서.. 결국 해결은 되지 않았음. netlify에서만 지원하는 기능이라고 추측 중.

추가로 현재 시도해볼 방법은 팀원인 형수님의 외부 https 서버 호스팅 시스템 구축 또는 notion api 활용이다.
notion api의 경우 cors를 지원하지 않는다고 하는데, 일단 https request가 가능하다는 점에서 시도해볼 가치는 있다고 생각.

**Comment by changgihong** [comment]
백엔드 팀원 형수님이 외부 https 기반 api 서버를 호스팅하는데 성공하셨으나, 해당 서버에서 원래 데이터를 받아오는 공공 api 서버로 request 전송 시 간헐적 에러 발생. (이유 불명)

따라서 공공 api가 전송할 수 있는 전체 데이터를 직접 내려받아서 DB 구축 및 api 서버에 연동 후 (형수님 작업),
변화된 스키마에 맞춰서 프론트에서 대응 작업을 수행하였고, vercel 상에서 단위 테스트 수행 결과 vercel에서 더 이상 Mixed Content Error를 발생시키지 않았음. (Issue Closed)

단, 크롬 브라우저 상에서 아직 Warning 수준의 Mixed Content 메시지를 띄우는데, 이는 api 서버가 보내주는 data를 기반으로 표시하는 Content들(수어 영상 thumbnail, 수형 사진)이 http 프로토콜을 통해 로드되기 때문. 이건 원천적인 문제라 더 손쓸 수 없을 듯 하다...

정리하면 다음과 같다.
검색 기능 수행 불가 시점 (Mixed Content) : https(vercel) -> http(Open API)
검색 기능 수행 가능 시점 (Mixed Content) : https(vercel) -> https(custom api server) -> http(data)
